name: Use Python application reusable workflow

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Python application reusable workflow
        uses: ./.github/workflows/python-app.yml
        with:
          python-version: '3.9'  # Specify the Python version you need
          script: 'your_script.py'
